pages:
  image: alpine:latest
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master

build:
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  services:
  - name: docker:dind
    alias: docker
  stage: deploy
  script:
  - echo $DOCKER_PW | docker login --username supporterino --password-stdin
  - docker build -t supporterino/discord_bots:latest .
  - docker push supporterino/discord_bots

sast:
  stage: .post
include:
- template: Security/SAST.gitlab-ci.yml
